language: python
sudo: required
dist: xenial
python: "3.7"
cache: pip
services:
  - postgresql

addons:
  firefox: "63.0"
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433

before_install:
  - pip install -r requirements.txt

before_script:
  - python3 -m flake8 --ignore E302 .
  - python3 -m pydocstyle .
  - psql -c 'create database demo-payment;' -U postgres

notifications:
  email:
    on_failure: change
