language: python
sudo: required
dist: xenial
python: "3.7"
cache: pip

services:
  - postgresql

addons:
  firefox: "63.0"

before_install:
  - pip install -r requirements.txt

before_script:
  - python3 -m flake8 --ignore E302 .
  - python3 -m pydocstyle .
  - psql -c 'create database demo_payment;' -U postgres

script:
  - pytest

notifications:
  email:
    on_failure: change
