version: '3'
services:
  demo_payment:
    build:
      context: ../
    ports:
      - "8889:8889"
    command: ./dev/run.sh --dbhost=db
    volumes:
      - ../:/demo-payment-server
    depends_on:
      - db
  db:
    image: postgres:10.6
    environment:
      POSTGRES_DB: demo_payment
