version: '3'
services:
  demo_payment:
    image: jmb2341/demo-payment-server:0.0.7
    command: ./prod/run.sh --dbhost=db --url=https://www.example.com
    depends_on:
      - db
  db:
    image: postgres:10.6
    environment:
      POSTGRES_DB: demo_payment
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp:/tmp
      - /var/www
    depends_on:
      - demo_payment
